services:
  mongodb:
    image: mongo:7
    container_name: franchise-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  franchise-api:
    build: .
    container_name: franchise-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/franchise-db
    depends_on:
      - mongodb

volumes:
  mongo_data: